app_secret:
  comment: '应用程序secret'
  secret: true

redirect_url:
  comment: '重定向URL'

movies_path:
  comment: '电影目录'
  value: '/OneMovie/Movies'

tv_series_path:
  comment: '剧集目录'
  value: '/OneMovie/TV-Series'
