language:
  value: 'zh-cn'
  field: 'params'
  comment: '语言-地区'

include_adult:
  comment: '搜索是否包含成人内容'
  value: 'false'
  field: 'params'

Authorization:
  field: 'headers'
  comment: 'Bearer Token'
  secret: true

proxies:
  type: 'dict'
  value: {}
  comment: '代理配置'
